name: Testing

on: push

jobs:
  my-job:
    name: More Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse HEAD)"
          echo "::set-env name=project_name::${GITHUB_REPOSITORY#*/}-${GITHUB_SHA:0:7}"
      - name: Another step
        run: |
          echo "Branch: ${{ steps.vars.outputs.branch }}"
          echo "Sha: ${{ steps.vars.outputs.sha_short }}"
          echo "Name: ${{ steps.vars.outputs.project_name }}"